version: 2.1

description: Build, preview and publish Leanpub books

executors:
  leanpub-executor:
    docker:
      - image: circleci/buildpack-deps

# Most commands and jobs use these parameters
base-leanpub-params: &base-leanpub-params
      book-slug:
        description: Slug of the book
        type: string
        default: $CIRCLE_PROJECT_REPONAME
      api-key:
        description: Your Leanpub API key
        type: env_var_name
        default: LEANPUB_API_KEY

jobs:

  subset-preview:
    description: >
      Produce a "subset preview", which generates only the PDF.
    parameters: *base-leanpub-params
    executor: leanpub-executor
    steps:
      - trigger-subset-preview:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>

  full-preview:
    description: >
      Produce a "full preview", which generates all the formats
      supported by Leanpub.
    parameters: *base-leanpub-params
    executor: leanpub-executor
    steps:
      - trigger-full-preview:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>

  publish:
    description: >
      Publish the book, with optional email of release notes. If the
      release-notes parameter is given, its contents is used as the
      release notes to send. If no release notes are given, a "silent
      publish" is done.
    parameters:
      <<: *base-leanpub-params
      release-notes:
        type: string
        default: ""
    executor: leanpub-executor
    steps:
      - trigger-publish:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>
          release-notes: <<parameters.release-notes>>

  auto-publish:
    description: >
      Publish the book, optionally sending out release notes gathered
      from git. If this job is triggered on a commit that has an
      annotated tag, the tag message is used as release notes. If it
      is triggered on an unannotated tag, the commit message from the
      tagged commit is used. If the job is called on a non-tagged
      commit, or if the auto-release-notes parameter is set to false
      (its default value), then the release notes are not produced.
    parameters:
      <<: *base-leanpub-params
      auto-release-notes:
        description: Produce release notes if a tag is available
        type: boolean
        default: false
      dry-run:
        description: Echo the command instead of running it?
        type: boolean
        default: false
    executor: leanpub-executor
    steps:
      - check-env-var-param:
          param: <<parameters.api-key>>
          error-message: "Please provide your Leanpub API key in environment variable <<parameters.api-key>>."
      - checkout
      - run:
          name: Publish book
          command: |
            export ECHO_CMD=<<#parameters.dry-run>>echo<</parameters.dry-run>>
            export RELEASE_NOTES=<<# parameters.auto-release-notes>>$([[ -n "$CIRCLE_TAG" ]] && git cat-file -p `git rev-parse $CIRCLE_TAG` | sed '1,/^$/d')<</ parameters.auto-release-notes>>
            if [[ -n "$RELEASE_NOTES" ]]; then
              $ECHO_CMD curl -d "api_key=${<<parameters.api-key>>}" -d "publish[email_readers]=true" --data-urlencode "publish[release_notes]=$RELEASE_NOTES" https://leanpub.com/<<parameters.book-slug>>/publish.json
            else
              $ECHO_CMD curl -d "api_key=${<<parameters.api-key>>}" https://leanpub.com/<<parameters.book-slug>>/publish.json
            fi

commands:
  # Generic entry point for triggering a Leanpub API call
  api-call:
    description: Trigger a Leanpub API call according to the endpoint parameter.
    parameters:
      <<: *base-leanpub-params
      endpoint:
        description: Path of the API endpoint without .json at the end
        type: string
      extra-params:
        description: Extra parameters to pass to the curl command
        type: string
        default: ""
      dry-run:
        description: Echo the command instead of running it?
        type: boolean
        default: false
    steps:
      - check-env-var-param:
          param: <<parameters.api-key>>
          error-message: "Please provide your Leanpub API key in environment variable <<parameters.api-key>>."
      - run:
          name: Call Leanpub API /<<parameters.endpoint>>.json
          command: |
            <<#parameters.dry-run>>echo <</parameters.dry-run>>curl -d "api_key=${<<parameters.api-key>>}" <<parameters.extra-params>> https://leanpub.com/<<parameters.book-slug>>/<<parameters.endpoint>>.json

  trigger-subset-preview:
    description: Trigger a subset (PDF only) preview.
    parameters: *base-leanpub-params
    steps:
      - api-call:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>
          endpoint: preview/subset

  trigger-full-preview:
    description: Trigger a full preview (all formats).
    parameters: *base-leanpub-params
    steps:
      - api-call:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>
          endpoint: preview

  trigger-publish:
    description: Trigger publishing, with optional sending of release notes if the release-notes parameter is specified.
    parameters:
      <<: *base-leanpub-params
      release-notes:
        description: Contents of the release notes to be sent out
        type: string
        default: ""
    steps:
      - api-call:
          book-slug: <<parameters.book-slug>>
          api-key: <<parameters.api-key>>
          endpoint: publish
          extra-params: <<# parameters.release-notes>>-d "publish[email_readers]=true" --data-urlencode "publish[release_notes]=<<parameters.release-notes>>"<</ parameters.release-notes >>
